const config = {
  symptomes: [
    "Pulsating",
    "Sensitivity to light",
    "Sensitivity to sound",
    "Sensitivity to smells",
    "Nausea",
    "Vomiting",
    "Stress",
    "Drowsiness",
    "Dizziness",
    "Vertigo",
    "Tension",
    "Numbness",
    "Visual disturbances",
    "Hallucinations",
    "Blurred vision",
    "Blind spots",
    "Tunnel vision",
    "Aura",
  ],
  locations: [
    "Forehead",
    "Temples",
    "Crown of the head",
    "Left eye",
    "Right eye",
    "Arms",
    "Legs",
    "Neck/shoulder",
    "Sinuses",
    "Jaw"
  ],
  medications: [
    "Acetaminophen (Tylenol)",
    "Aspirin",
    "Ibuprofen (Advil, Motrin)",
    "Naproxen (Aleve)",
    "Triptans (sumatriptan, rizatriptan, etc.)",
    "Ergotamines (dihydroergotamine, ergotamine tartrate)",
    "Opioids (codeine, oxycodone, hydrocodone)",
    "Butalbital-containing medications (Fiorinal, Fioricet)",
    "Preventive medications (beta blockers, calcium channel blockers, etc.)",
    "Antidepressants (amitriptyline, venlafaxine, etc.)",
    "Antiepileptic drugs (topiramate, valproic acid, etc.)",
    "Botox injections",
    "CGRP monoclonal antibodies (erenumab, fremanezumab, etc.)",
  ],
};

export default config;
